# Selection Colors
selection_foreground     #c0caf5
selection_background     #2e3c64

# Window border Colors
active_border_color      #7aa2f7
inactive_border_color    #292e42

# Kitty tabs colors
active_tab_foreground    #1f2335
active_tab_background    #7aa2f7
inactive_tab_foreground  #545c7e
inactive_tab_background  #292e42

# Basic color
background               #24283b
foreground               #c0caf5

# 16 main colors
color0                   #1d202f
color1                   #f7768e
color2                   #9ece6a
color3                   #e0af68
color4                   #7aa2f7
color5                   #bb9af7
color6                   #7dcfff
color7                   #a9b1d6
color8                   #414868
color9                   #ff899d
color10                  #9fe044
color11                  #faba4a
color12                  #8db0ff
color13                  #c7a9ff
color14                  #a4daff
color15                  #c0caf5

# Cursor colors
cursor                   #c0caf5
cursor_text_color        #24283b

# Url color
url_color                #73daca
